# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [3]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [7]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [8]:
arr2 = np.zeros((4,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [9]:
sevens = np.full((3,5), 7)
sevens

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [11]:
ten_to_seven = np.arange(10, 70, 5)
ten_to_seven

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [12]:
np.linspace(10, 20, 15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [16]:
np.random.randint(0,10, (3,5))

array([[7, 6, 2, 1, 5],
       [4, 3, 4, 8, 2],
       [7, 2, 7, 7, 6]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [22]:
arrs = np.arange(0,24)
arrs = arrs.reshape((4,6))
arrs

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [42]:
a = np.random.random(10)
print(a.max())
print(a.min())

0.876236412666361
0.09377328673561491


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [4]:
my_arr = np.random.randint(0,36, (6,6))
my_arr

array([[20, 11,  2, 14,  0, 11],
       [ 5, 30,  3, 14,  6, 19],
       [15, 19, 26, 27, 23, 20],
       [ 6, 31, 10,  1, 10, 34],
       [18, 29,  4,  9, 19, 14],
       [23, 20,  0, 35, 14, 29]])

12- 5.satırdaki elemanları gösteriniz.

In [5]:
my_arr[4,:]

array([18, 29,  4,  9, 19, 14])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [6]:
print(my_arr[5,:])
print(my_arr[:,5])

[23 20  0 35 14 29]
[11 19 20 34 14 29]


14-4.sutundaki tüm elemanları çekin.

In [7]:
col_4 = my_arr[:,3]
col_4

array([14, 14, 27,  1,  9, 35])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [12]:
for i in (my_arr):
    print(my_arr.flat[i])

[10 19  2 26 20 19]
[11 23 14 26  5 31]
[27 31  4  9 34 10]
[ 5 20  6 11  6 14]
[ 6 14  0 14 31 26]
[34 10 20 29 26 14]


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [21]:
my_arr2 = np.random.random((2,2))
my_arr2
my_arr2 *= 5
my_arr2

array([[1.47099938, 1.69655402],
       [2.35098089, 3.06863726]])

16- Satırların toplam değeri nedir?

In [26]:
np.sum(my_arr2, axis = 1)

array([3.1675534 , 5.41961815])

17-Satırların standart sapma değeri nedir?

In [27]:
np.std(my_arr2, axis = 1)

array([0.11277732, 0.35882819])

18-Satırların varyans değeri nedir?

In [28]:
np.var(my_arr2, axis = 1)

array([0.01271872, 0.12875767])

19- Satırların transpoz değeri nedir?

In [29]:
my_arr2.transpose()

array([[1.47099938, 2.35098089],
       [1.69655402, 3.06863726]])